version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
    open-pull-requests-limit: 10
    labels:
      - "type: dependency-upgrade"
